export default {
	'en-US': `USD`,
	'de-DE': `EUR`,
	'nl-BE': `EUR`,
	'fr-BE': `EUR`,
	'sg-SG': `SGD`,
	'my-MY': `MYR`,
	'tr-TR': `TRY`,
	'fr-FR': `EUR`,
	'th-TH': `THB`,
	'ru-RU': `RUB`,
	'vi-VN': `VND`,
	'pt-BR': `BRL`,
	'ja-JP': `JPY`,
	'zh-HK': `HKD`,
	'en-IN': `INR`,
	'en-GB': `GBP`,
	'ko-KR': `KRW`,
	'zh-TW': `TWD`,
	'zh-CN': `CNY`,
};